environment: "dev"

firebase:
  project: "cwb05-dev"

net:
  host: "agency-dev.cwb05.dsgov.demo.nuvalence.io"

environmentJSON: {
  authenticationConfiguration: {
    firebaseConfiguration: {
      firebase: {
        apiKey: "AIzaSyB_SiZqAwS4z0GLV8sVZv6-4OO5xy-H-SE",
        authDomain: "cwb05-dev.dsgov.demo.nuvalence.io",
      },
      tenantId: 'agency-portal-ibtho',
    },
    sessionExpiration: {
      idleTimeSeconds: 1800,
      sessionTimeSeconds: 64800,
    },
  },
  httpConfiguration: {
    baseUrl: "https://api-dev.cwb05.dsgov.demo.nuvalence.io",
  },
}
